### PR TITLE
Fix build on kernel 6.0+

### PR DESCRIPTION
**Pull request by NickCao**

### CODE REVIEW

**Comment by NickCao** [comment]
Fixes https://github.com/PlatformLab/HomaModule/issues/14

**Comment by johnousterhout** [comment]
Thanks for providing these changes; I've created a new branch linux_6.0 that includes them. I don't currently have a Linux 6.0 installation to test these on; if you have a chance to try them out, that would be great.

Also, if you don't mind saying, I'd be curious to know what you are doing with Homa.

**Comment by NickCao** [comment]
I'm writing a [nccl net plugin](https://github.com/NVIDIA/nccl/tree/master/ext-net) utilizing homa, and the current works are here: [rust binding](https://github.com/NickCao/roma) and [plugin](https://github.com/NickCao/penny)

**Comment by johnousterhout** [comment]
Thanks for the information.

-John-

**Pull request closed without merging**
